#!/usr/bin/env -S dotnet fsi --exec

(*

https://projecteuler.net/problem=2
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*)

open System.Diagnostics

let sw = Stopwatch.StartNew()

let rec fib last current sum =
    if current >= 4_000_000 then
        sum
    else
        fib
            current
            (current + last)
            (sum + (if current % 2 = 0 then current else 0))

printfn $"%d{fib 1 2 0}"

sw.Stop()

printfn $"took %f{1000. * (float sw.ElapsedTicks) / (float Stopwatch.Frequency)}ms"